### ISSUE TITLE
This lib is not thread safe

### ISSUE THREAD

**Issue by ducnguyen2595** [prozz/aws-embedded-metrics-golang#15]
I tried to run inside multiple goroutine and got this
```

fatal error: concurrent map writes
goroutine 652 [running]:


github.com/prozz/aws-embedded-metrics-golang@v1.2.0/emf/logger.go:170 
github.com/prozz/aws-embedded-metrics-golang/emf.(*Context).put(...)

github.com/prozz/aws-embedded-metrics-golang@v1.2.0/emf/logger.go:298 
github.com/prozz/aws-embedded-metrics-golang/emf.(*Logger).MetricAs(...)
```

**Comment by ducnguyen2595** [comment]
it doesn't maintain the structure correctly
```
{
    "ServiceName": "lambda",
    "ServiceType": "AWS::Lambda::Function",
    "_aws": {
        "Timestamp": 1732262792649,
        "CloudWatchMetrics": [
            {
                "Namespace": "DUC_NameSPace",
                "Dimensions": [
                    [
                        "ServiceName",
                        "ServiceType"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceA_latency",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "serviceB_latency",
                        "Unit": "Milliseconds"
                    }
                ]
            }
        ]
    },
    "executionEnvironment": "",
    "functionVersion": "$LATEST",
    "logStreamId": "2024/11/22/lambda[$LATEST]bdadc1955116469bb7d300bed19fb483",
    "memorySize": "256",
    "serviceA_latency": 650758,
    "serviceB_latency": 0
}
```

**Comment by ducnguyen2595** [comment]
just notice 
each struct supposed to be used for one metric at denote in README, keep this here in case you have the same issue.
```
emf.New().Namespace("mtg").Metric("totalWins", 1500).Log()

emf.New().Dimension("colour", "red").
    MetricAs("gameLength", 2, emf.Seconds).Log()

emf.New().DimensionSet(
        emf.NewDimension("format", "edh"),
        emf.NewDimension("commander", "Muldrotha")).
    MetricAs("wins", 1499, emf.Count).Log()
```
